# Generated by Django 5.0.2 on 2024-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.CharField(default=2333334, max_length=15),
            preserve_default=False,
        ),
    ]
